version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
  app:
    build: .
    command: sh -c "sleep 10 && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db

# Connect to the database from cmd
# docker exec -it <CONTAINER_ID> psql -U admin -d walletwatch_db
